name: fhir_health_equity
version: 1.0.0
config-version: 2

profile: fhir_health_equity

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fhir_health_equity:
    bronze:
      +materialized: view
      +schema: bronze_models
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

